DROP TABLE QUESTAOALTERNATIVA;
DROP TABLE QUESTAODISSERTATIVA;
DROP TABLE QUESTAO_PROVA;
DROP TABLE PROVA_QUESTAO;
DROP TABLE PROFESSOR_PROVA;
DROP TABLE PROVA_DISCIPLINA;
DROP TABLE PROFESSOR_DISCIPLINA;
DROP TABLE PROFESSOR;
DROP TABLE PROVA_CONTEUDO;
DROP TABLE PROVA;
DROP TABLE QUESTAOVERDADEIROFALSO;
DROP TABLE QUESTAO;
DROP TABLE CONTEUDO;
DROP TABLE DISCIPLINA;
DROP TABLE SEQUENCE;

SELECT * FROM QUESTAO;
SELECT * FROM DISCIPLINA;
SELECT * FROM CONTEUDO;