select * from QUESTAO;
drop table QUESTAOALTERNATIVA;
drop table QUESTAODISSERTATIVA;
DROP TABLE QUESTAO_PROVA;
DROP TABLE PROVA_QUESTAO;
DROP TABLE CONTEUDO_QUESTAO;
DROP TABLE QUESTAO;

DROP TABLE DISCIPLINA_CONTEUDO;
DROP TABLE PROFESSOR_DISCIPLINA;
DROP TABLE PROVA_DISCIPLINA;
DROP TABLE DISCIPLINA;

DROP TABLE PROFESSOR_PROVA;
DROP TABLE PROFESSOR;

DROP TABLE CONTEUDO_PROVA;
DROP TABLE PROVA_CONTEUDO;
DROP TABLE CONTEUDO;

DROP TABLE PROVA;

DROP TABLE SEQUENCE;

SELECT * FROM DISCIPLINA;
SELECT * FROM CONTEUDO;