DROP TABLE QUESTAOALTERNATIVA;
DROP TABLE PROVA_QUESTOES;
DROP TABLE QUESTAODISSERTATIVA;
DROP TABLE PROVA_QUESTOES;
DROP TABLE PROFESSOR_PROVA;
DROP TABLE PROFESSOR_DISCIPLINA;
DROP TABLE PROFESSOR;
DROP TABLE PROVA_CONTEUDOS;
DROP TABLE PROVA;
DROP TABLE QUESTAOVERDADEIROFALSO;
DROP TABLE ALTERNATIVA;
DROP TABLE QUESTAO;
DROP TABLE CONTEUDO;
DROP TABLE DISCIPLINA;
DROP TABLE SEQUENCE;

SELECT * FROM QUESTAO;
SELECT * FROM DISCIPLINA;
SELECT * FROM CONTEUDO;



INSERT INTO DISCIPLINA (ID,NOME) values(1,'Biologia');
INSERT INTO DISCIPLINA (ID,NOME) values(2,'Química');
INSERT INTO DISCIPLINA (ID,NOME) values(3,'OOP');
INSERT INTO DISCIPLINA (ID,NOME) values(4,'EDA');
INSERT INTO DISCIPLINA (ID,NOME) values(5,'Banco de Dados');


INSERT INTO CONTEUDO (ID,TOPICO,DISCIPLINA_ID) values (6,'Tabela Periódica',2);
INSERT INTO CONTEUDO (ID,TOPICO,DISCIPLINA_ID) values (7,'Algoritmo de Árvores Binárias',4);
INSERT INTO CONTEUDO (ID,TOPICO,DISCIPLINA_ID) values (8,'Grafo',4);
INSERT INTO CONTEUDO (ID,TOPICO,DISCIPLINA_ID) values (9,'Atomicidade',2);
INSERT INTO CONTEUDO (ID,TOPICO,DISCIPLINA_ID) values (10,'Seletividade Natural',1);
INSERT INTO CONTEUDO (ID,TOPICO,DISCIPLINA_ID) values (11,'UML',5);